### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/vertikin#4]
create a file for **server** for including all the dependencies

**Comment by Kashyap12** [comment]
Hi @prabhakar267 , relatively new to open source, can I take this up?

**Comment by prabhakar267** [comment]
@Kashyap12 Yes you can do go ahead.
Feel free to ping me if you face any problem.
Hint: You will need to setup a virtual environment.

**Comment by Kashyap12** [comment]
hi @prabhakar267 , do u have a gitter chat or an IRC channel where we can chat? Need some clarification

**Comment by prabhakar267** [comment]
You can send me a mail at prabhakargupta267@gmail.com and we can chat there.

**Comment by andrewseaman35** [comment]
Hey @prabhakar267 , is this up for grabs? I don't see a PR for it and would like to contribute.
